name: Keep Alive

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes

jobs:
  keep-alive-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run keep_alive script
        run: |
          chmod +x keep_alive.sh
          ./keep_alive.sh
