name: Keep Alive

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes

jobs:
  keep-alive-job:
    runs-on: windows-latest  # Ensure it runs on a Windows environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run keep_alive.bat
        shell: cmd
        run: |
          keep_alive.bat
